INSERT INTO POWERS(POWER_ID, NAME) VALUES (1, 'Invisibility')
INSERT INTO POWERS(POWER_ID, NAME) VALUES (2, 'Super strength')
INSERT INTO POWERS(POWER_ID, NAME) VALUES (3, 'Fly')


INSERT INTO HEROES(ID, NAME, ALTER_EGO, POWER_ID) VALUES (12,  'Dr. Nice' , 'Joker', 1)
INSERT INTO HEROES(ID, NAME, ALTER_EGO, POWER_ID) VALUES (13,  'Bombasto' , 'Thanos', 2)
INSERT INTO HEROES(ID, NAME, ALTER_EGO, POWER_ID) VALUES (14,  'Celeritas' , 'Voldemort', 3)
INSERT INTO HEROES(ID, NAME, ALTER_EGO, POWER_ID) VALUES (15,  'Magneta' , 'Joker', 1)
INSERT INTO HEROES(ID, NAME, ALTER_EGO, POWER_ID) VALUES (16,  'RubberMan' , 'Thanos', 2)
INSERT INTO HEROES(ID, NAME, ALTER_EGO, POWER_ID) VALUES (17,  'Dynama' , 'Joker', 3)
INSERT INTO HEROES(ID, NAME, ALTER_EGO, POWER_ID) VALUES (18,  'Dr. IQ' , 'Voldemort', 1)
INSERT INTO HEROES(ID, NAME, ALTER_EGO, POWER_ID) VALUES (19,  'Magma' , 'Thanos', 2)
INSERT INTO HEROES(ID, NAME, ALTER_EGO, POWER_ID) VALUES (20,  'Tornado', 'Joker', 3)